nonilnil/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    # Examples:
    # url(r'^$', 'nonilnil.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'webapp/', include('webapp.urls')),
    # https://django-registration-redux.readthedocs.org/en/latest/
    url(r'^accounts/', include('registration.backends.default.urls')),

        #override the default urls
    url(r'^password/change/$',
                auth_views.password_change,
                name='password_change'),
    url(r'^password/change/done/$',
                auth_views.password_change_done,
                name='password_change_done'),
    url(r'^password/reset/$',
                auth_views.password_reset,
                name='password_reset'),
    url(r'^password/reset/done/$',
                auth_views.password_reset_done,
                name='password_reset_done'),
    url(r'^password/reset/complete/$',
                auth_views.password_reset_complete,
                name='password_reset_complete'),
    url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
                auth_views.password_reset_confirm,
                name='password_reset_confirm'),

]

webapp/urls.py
from django.conf.urls import url
from . import views

    # url(r'^blog/', include('blog.urls')),

# / 	               List of all Series, highest PK first
# /?P<pk>[0-9]+/       The series showing round by round, highest round PK first
# /?P<pk>[0-9]+/       

urlpatterns = [
    url(r'^$', views.series_list, name='series_list'),
    url(r'^(?P<pk>[0-9]+)/$', views.series_detail, name='series_detail'),
    url(r'^(?P<s_pk>[0-9]+)/(?P<r_pk>[0-9]+)/prediction/$', views.manage_prediction, name='manage_prediction'),
    url(r'^(?P<pk>[0-9]+)/l/$', views.loser_detail, name='loser_detail'),
    url(r'^(?P<s_pk>[0-9]+)/(?P<r_pk>[0-9]+)/nilnils/$', views.manage_nilnils, name='manage_nilnils'),
    url(r'^(?P<s_pk>[0-9]+)/(?P<r_pk>[0-9]+)/missing/$', views.missing_prediction, name='missing_prediction'),
    url(r'^(?P<s_pk>[0-9]+)/(?P<r_pk>[0-9]+)/ping/$', views.ping_email_message, name='ping_email_message'),
]

webapp/models.py
from django.db import models
from django.conf import settings 

from django.contrib.auth.models import User
from django.db.models import Sum

from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.mail import send_mail
from django.template import Context
from django.template.loader import render_to_string

# Create your models here.

class Fgroup(models.Model):
    # Include in Admin
    # examples, English League, champions league 2017
    DEFAULT_PK=1
    group_name = models.CharField(max_length=200, help_text='Name of group, e.g. Champions League')

    def __str__(self):              # __unicode__ on Python 2
        return self.group_name

class Team(models.Model):
    # Include in Admin
    # The list of eligable teams, e.g. English football
    # Some team may drop out of the league  - tough luck
    fgroup = models.ForeignKey(Fgroup, on_delete=models.CASCADE, default=Fgroup.DEFAULT_PK)
    team_name = models.CharField(max_length=200, help_text='Name of Team')

    def __str__(self):              # __unicode__ on Python 2
        return self.team_name

    class Meta:
        ordering = ['id']


class Series(models.Model):
    # Include in Admin
    series_name = models.CharField(max_length=200, help_text='Name of series of games')
    series_open = models.BooleanField(default=True)
    entry_cost = models.DecimalField(max_digits=5, decimal_places=2)
    rollover = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    end_message = models.TextField(null=True, blank=True, help_text="A Message to include at end of series (e.g. Winner: HHH, after 8 rounds")

    def __str__(self):              # __unicode__ on Python 2
        return self.series_name
    def paid(self):
        paid = Payment.objects.filter(series=self.id, paid=True)
        return paid
    def naughty(self):
        paid_users = Payment.objects.filter(series=self.id, paid=True).values('user')
        round_f = Round.objects.filter(series=self.id)
        naughty_users = Prediction.objects.filter(round_f=round_f).exclude(user=paid_users)
        return naughty_users
    def spectators(self):
        spectators = User.objects.exclude(id__in =self.paid().values_list('user')).exclude(id__in =self.naughty().values_list('user'))
        return spectators
    def expected_prize_pot(self):
        payment_total = self.paid().aggregate(Sum('payment')).get('payment__sum')
        return payment_total + self.rollover + (len(self.naughty()) * self.entry_cost)

    class Meta:
        ordering = ['-id']
  
class Round(models.Model):
    # Include in Admin
    series = models.ForeignKey(Series, on_delete=models.CASCADE)
    round_date = models.DateTimeField('Date games will be played on')
    round_open = models.BooleanField(default=True)
    email_message = models.TextField(null=True, blank=True, help_text="A Message to include in the email")

    def staff_predictions(self):
        p = Prediction.objects.filter(round_f=self.id).filter(user__is_staff=1)
        return p

    def __str__(self):              # __unicode__ on Python 2
        return self.series.series_name + " " + str(self.round_date)
    class Meta:
        ordering = ['-round_date']


class Emailround(models.Model):
    # Include in Admin in case of error.
    # Slowly notify users of new round. 
    # Cron job ?
    round_f = models.ForeignKey(Round, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    sent = models.BooleanField(default=True)

class Payment(models.Model):
    # Include in Admin
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    series = models.ForeignKey(Series, on_delete=models.CASCADE)
    paid = models.BooleanField(default=False)
    payment = models.DecimalField(max_digits=5, decimal_places=2, default=5)
    class Meta:
        ordering = ['series']

    def __str__(self):              # __unicode__ on Python 2
        return str(self.user) + " " + str(self.series) + " " + str(self.payment)

@receiver(post_save, sender=Payment, dispatch_uid="update_payment")
def update_payment(sender, instance, **kwargs):
    payment = instance
    message = "Payment received, £" + str(payment.payment) + ". You are now off the naughty step."
    c = Context({'message': message, 'user': payment.user,}) 
    text_content = render_to_string('email/payment.txt', c)
    subject = "NoNilNil - Payment received for " + str(payment.series)
    send_mail(subject, text_content, "NoNilNil Payments <no-reply@NoNilNil.com>", [payment.user.email], fail_silently=False)


class Prediction(models.Model):
    # User form - the only one ?
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    round_f = models.ForeignKey(Round, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)

    def __str__(self):              # __unicode__ on Python 2
        return str(self.user) + " " + str(self.round_f) + " " + str(self.team)
    def failed(self):
        possible_nilnils = Nilnils.objects.filter(round_f=self.round_f, team=self.team)[:1]
        if possible_nilnils:
            return(Nilnils.objects.get(round_f=self.round_f, team=self.team).ohno)
        else:
            return(False)
    class Meta:
        ordering = ['round_f']


class Nilnils(models.Model):
    # Superuser form, list teams select from that round and edit the ohno by exception
    round_f = models.ForeignKey(Round, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE, null=False)
    ohno = models.BooleanField(default=False)

    def __str__(self):              # __unicode__ on Python 2
        return str(self.round_f) + " " + str(self.team) + " " + str(self.ohno)
    class Meta:
        ordering = ['round_f']

webapp/forms.py
from django import forms

from .models import Prediction

class PredictionForm(forms.ModelForm):

    class Meta:
        model = Prediction
        fields = ('team',)


class EmailOutForm(forms.Form):
    message = forms.CharField(widget=forms.Textarea)
    send_to_all = forms.BooleanField(required=False)

webapp/views.py
from django.shortcuts import get_object_or_404, render, redirect

from django.forms import modelformset_factory
from django.utils import timezone
from django.core.mail import send_mail
from django.template import Context
from django.template.loader import render_to_string
from django.conf import settings

from .models import Series
from .models import Round
from .models import Prediction
from .models import Nilnils

from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required

from django.contrib.auth import get_user_model
User = get_user_model()

from .forms import PredictionForm
from .forms import EmailOutForm

# Create your views here.

def series_list(request):
    series = Series.objects.order_by('-id')
    context = {'series': series}
    return render(request, 'webapp/index.html', context)

def series_detail(request, pk):
    series = get_object_or_404(Series, id=pk)
    round_f = Round.objects.filter(series=series).order_by('-id')
    return render(request, 'webapp/detail.html', {'series': series, 'round_f': round_f})

def loser_detail(request, pk):
    series = get_object_or_404(Series, id=pk)
    round_f = Round.objects.filter(series=series).order_by('-id')
    return render(request, 'webapp/detail.html', {'series': series, 'round_f': round_f, 'loser': True})

@staff_member_required
def missing_prediction(request, s_pk, r_pk):
    round_f = get_object_or_404(Round, id=r_pk)
    u_all = User.objects.all()
    prediction_empty = []
    for u in u_all:
        not_empty = len(Prediction.objects.filter(round_f=round_f, user_id=u))
        if not not_empty:
            prediction_empty.append(u.username)

    PredictionFormSet = modelformset_factory(Prediction, fields=('team', 'user'), extra=len(prediction_empty))
    if request.method == 'POST':
        formset = PredictionFormSet(request.POST, request.FILES, queryset=Prediction.objects.none())
        if formset.is_valid():
            for form in formset:
                if form.is_valid():
                    prediction = form.save(commit=False)
                    prediction.round_f_id = round_f.id
                    try:
                        prediction.save()
                    except:
                        pass
            return redirect('missing_prediction', s_pk=s_pk, r_pk=r_pk)

    else:
        formset = PredictionFormSet(queryset=Prediction.objects.none())

    return render(request, 'webapp/missing_prediction.html', {'prediction_empty': prediction_empty, 'round_f': round_f, 'formset': formset, 's_pk': s_pk})


@staff_member_required
def ping_email_message(request, s_pk, r_pk):
    round_f = get_object_or_404(Round, id=r_pk)
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = EmailOutForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            message = form.cleaned_data['message']
            send_to_all = form.cleaned_data['send_to_all']
            users = []
            if send_to_all:
                users = list(User.objects.all())
            else:
                users.append(request.user)
            for user in list(users):
                c = Context({'message': message, 'user': user, 'round_f': round_f,})    
                text_content = render_to_string('email/round_email.txt', c)
                subject = 'NoNilNil - ' + str(round_f.series)
                send_mail(subject, text_content, "NoNilNil News <no-reply@NoNilNil.com>", [user.email], fail_silently=False)
            if send_to_all:
                round_f.email_message = message
                round_f.save()
            return redirect('series_detail', pk=s_pk)
    # if a GET (or any other method) we'll create a blank form
    else:
        form = EmailOutForm()
    return render(request, 'webapp/email_edit.html', {'form': form, 'round_f': round_f, 's_pk': s_pk})


@staff_member_required
def manage_nilnils(request, s_pk, r_pk):
    round_f = get_object_or_404(Round, id=r_pk)
    predictions_all_users = Prediction.objects.filter(round_f=round_f)
    total_team = len( Prediction.objects.filter(round_f=round_f).values('team'))
    print(predictions_all_users, Prediction.objects.filter(round_f=round_f).values('team') )
    NilnilsFormSet = modelformset_factory(Nilnils, fields=('team', 'ohno'), max_num=total_team)
    if request.method == 'POST':
        formset = NilnilsFormSet(request.POST, request.FILES, queryset=Nilnils.objects.filter(round_f=r_pk))
        if formset.is_valid():
            for form in formset:
                    nilnil = form.save(commit=False)
                    nilnil.round_f = round_f
                    nilnil.save()
    else:
        formset = NilnilsFormSet(queryset=Nilnils.objects.filter(round_f=r_pk))
    return render(request, 'webapp/nilnil_edit.html', {'formset': formset, 'all_predictions': predictions_all_users, 'round_f': round_f, 's_pk': s_pk})

@login_required
def manage_prediction(request, s_pk, r_pk):
    round_f = get_object_or_404(Round, id=r_pk)
    PredictionFormSet = modelformset_factory(Prediction, fields=('team', ), max_num=1)
    message = ""
    all_rounds = Round.objects.filter(series=round_f.series.id)
    all_predictions = Prediction.objects.filter(round_f=all_rounds, user=request.user)
    for prediction in all_predictions:
       if prediction.failed():
           return redirect('loser_detail', pk=s_pk)

    if request.method == "POST":
        formset = PredictionFormSet(request.POST, request.FILES,
                                queryset=Prediction.objects.filter(round_f=r_pk, user=request.user))
        if timezone.now() > round_f.round_date :
             message = "Too late for to make or change your prediction. "
#            return redirect('series_detail', pk=s_pk)
        if formset.is_valid():
            for form in formset:
                prediction = form.save(commit=False)
                try:
                    team_count = Prediction.objects.filter(round_f=all_rounds, team=prediction.team, user=request.user).count()
                    if team_count >0:
                        message += "You have already used " + str(prediction.team) + " in this series (or just re-saving your team)"
                except:
                    pass

        if formset.is_valid() and message == "":
            for form in formset:
                if form.is_valid():
                    prediction = form.save(commit=False)
                    prediction.user = request.user
                    prediction.round_f = round_f
                    try:
                        prediction.save()
                    except:
                        pass
            return redirect('series_detail', pk=s_pk)
    else:
        formset = PredictionFormSet(queryset=Prediction.objects.filter(round_f=r_pk, user=request.user))
    return render(request, 'webapp/prediction_edit.html', {'formset': formset, 'round_f': round_f, 'message': message, 'all_predictions': all_predictions, 's_pk': s_pk})

webapp/templates/webapp/detail.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

{% if loser %}
<h1>Losers can not enter any more teams until the next series starts</h1>

{% endif %}

<h4>{{ series.series_name }}</h4>
    {% if not series.series_open %}
        <h5>This is now closed</h5>
        <p>{{ series.end_message }}</p>
    {% endif %}

    {% if series.series_open %}
        <h4>This is still open - what fun</h4>
        <p>Cost of entry £{{ series.entry_cost }} with a added roll-over of £{{ series.rollover }} <p>
    {% endif %}

    {% if round_f %}
        <h4>Rounds</h4>
        {% for round in round_f %}
            <div class="panel panel-default">
            {% if round.round_open %}
                <div class="panel-heading"><h4 class="panel-title"><a href="{% url 'manage_prediction' series.id round.id %}">Round still open until {{ round.round_date }} - enter your selection</a></h4></div>
                <div class="panel-body">
                {% if round.staff_predictions %}
                    <p>Website staff predictions are show ahead of the end date - so you can see no cheating</p>
                    <ul>
                    {% for prediction in round.staff_predictions %}
                        <li>{{ prediction.user }}, picked {{ prediction.team }}</li>
                    {% endfor %}
                    </ul>
                {% endif %}
            {% endif %}

            {% if not round.round_open %}
                <div class="panel-heading"><h4 class="panel-title">{{ round.round_date }} - Round Closed</h4></div>
                <div class="panel-body">
                {% for prediction in round.prediction_set.all %}
                    <ul><li>{{ prediction.user }}, picked {{ prediction.team }}, which {{ prediction.failed|yesno:"was Nil Nil!,had a goal,maybe - just maybe" }}</li></ul>
                {% endfor %}
            {% endif %}
            {% if user.is_staff %}
                <p><a href="{% url 'manage_nilnils' series.id round.id %}">Staff Only, mark games NilNil for {{ round.round_date }}</a></p>
                <p><a href="{% url 'missing_prediction' series.id round.id %}">Staff Only, mark missing prediction for {{ round.round_date }}</a></p>
                <p><a href="{% url 'ping_email_message' series.id round.id %}">Staff Only, send out email for {{ round.round_date }}</a></p>
            {% endif %}

            </div>
            </div>
        {% endfor %}
    {% endif %}


{% endblock %}

webapp/templates/webapp/email_edit.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

<h4>{{ round_f.round_date|date:"D d M Y" }} - {{ round_f.series.series_name }}</h4>

<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>

<p><a href="{% url 'series_detail' s_pk %}">Return to Game summary</a></p>
{% endblock %}

webapp/templates/webapp/index.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

{% if series %}
    {% for serie in series %}
      <div class="panel panel-default">
        <div class="panel-heading">
        <h4 class="panel-title"><a href="{% url 'series_detail' serie.id %}">{{ serie.series_name }} {% if not serie.series_open %}(Closed){% endif %}.</h4></a>
        </div>
        <div class="panel-body">
        {% if not serie.series_open %}(Closed).
            <ul><li>{{ serie.end_message }}</li></ul>
        {% endif %}
        {% if serie.series_open %}
            <h5>Expected prize pot of £{{ serie.expected_prize_pot }}</h5>
            {% if serie.paid %}
                <h5>The following people have paid for entry</h5>
                {% for p in serie.paid %}
                    <ul><li>{{ p.user }}</li></ul>
                {% endfor %}
            {% endif %}
            {% if serie.naughty %}
                <h5>The following people are naughty - they have made a prediction but not paid</h5>
                {% for p in serie.naughty %}
                    <ul><li>{{ p.user }}</li></ul>
                {% endfor %}
            {% endif %}
            {% if serie.spectators %}
                <h5>The following people are spectators of the show, (not paid, not predicted)</h5>
                {% for p in serie.spectators %}
                    <ul><li>{{ p.username }}</li></ul>
                {% endfor %}
            {% endif %}
        {% endif %}
        <p><a href="{% url 'series_detail' serie.id %}">View Details or add a prediction</a></p>
        </div>
      </div> 
    {% endfor %}
{% else %}
    <p>No games are available.</p>
{% endif %}
{% endblock %}



<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Panel title</h3>
  </div>
  <div class="panel-body">
    Panel content
  </div>
</div>

webapp/templates/webapp/missing_prediction.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

<h2>Missing Predictions {{ round_f.round_date|date:"D d M Y" }} - {{ round_f.series.series_name }}</h2>
{% if prediction_empty %}
    <ul>
    {% for p_e in prediction_empty  %}
        <li>{{ p_e }}</li>
    {% endfor %}
    </ul> 
{% endif %}

{% if message %}
    <p> {{ message }} </p>
{% endif %}
<form method="post" action="">
    {% csrf_token %}
    {% for form in formset.forms %}
        {{ form.non_field_errors }}
        {{ form.errors }}
        {{ form.as_p }}
    {% endfor %}
   {{ formset.management_form }} 
    <button type="submit">Save</button>

</form>

<p><a href="{% url 'series_detail' s_pk %}">Return to Game summary</a></p>

{% endblock %}

webapp/templates/webapp/nilnil_edit.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

<h4>Nil Nils for {{ round_f.round_date|date:"D d M Y" }} - {{ round_f.series.series_name }}</h4>
{% if all_predictions %}
    <h4>Saved predictions</h4>
    <ul>
    {% for prediction in all_predictions  %}
        <li>{{ prediction.round_f.round_date|date:"D d M Y" }}, {{ prediction.team }} {{ prediction.user }}</li>
    {% endfor %}
    </ul> 
{% endif %}

{% if message %}
    <p> {{ message }} </p>
{% endif %}
<form method="post" action="">
    {% csrf_token %}
    {% for form in formset.forms %}
        {{ form.non_field_errors }}
        {{ form.errors }}
    {% endfor %}
    {{ formset }}
    <button type="submit">Save</button>

</form>

<p><a href="{% url 'series_detail' s_pk %}">Return to Game summary</a></p>
{% endblock %}

webapp/templates/webapp/prediction_edit.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

<h2>Enter the prediction for games to be played on {{ round_f.round_date|date:"D d M Y" }} - {{ round_f.series.series_name }}</h2>
<p>On the day of the matches - the selected team can not be changed</p>
{% if all_predictions %}
    <h3>Saved predictions</h3>
    <ul>
    {% for prediction in all_predictions  %}
        <li>{{ prediction.round_f.round_date|date:"D d M Y" }}, {{ prediction.team }}</li>
    {% endfor %}
    </ul> 
{% endif %}

{% if message %}
    <p> {{ message }} </p>
{% endif %}
<form method="post" action="">
    {% csrf_token %}
    {% for form in formset.forms %}
        {{ form.non_field_errors }}
        {{ form.errors }}
    {% endfor %}
    {{ formset }}
    <button type="submit">Save</button>

</form>

{% endblock %}